# Generated by Django 4.1.1 on 2022-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag", name="name", field=models.CharField(max_length=100),
        ),
    ]
